/* IMPORTANT - \n\n *MUST* separate commands */ 
CREATE TABLE Albums (
	ID INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	Artist INTEGER NOT NULL,
	Name VARCHAR(255) NOT NULL,
	SortKey VARCHAR(255) NOT NULL
);

CREATE TABLE Artists (
	ID INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	Name VARCHAR(255) NOT NULL,
	RomanisedName VARCHAR(255) NOT NULL,
	SortKey VARCHAR(255) NOT NULL
);

CREATE TABLE Tracks (
	ID INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	FileName VARCHAR(255) NOT NULL,
	Album INTEGER NOT NULL,
	Artist INTEGER NOT NULL,
	Name VARCHAR(255) NOT NULL,
	TrackNumber INT NOT NULL,
	AlbumRG FLOAT NOT NULL,
	SearchKey VARCHAR(255) NOT NULL,
	TrackRG FLOAT NOT NULL,
	MusicBrainzTrackID CHAR(36) NOT NULL
);

CREATE VIEW TrackData AS
	SELECT
		Tracks.ID AS ID,
		Tracks.FileName AS FileName,
		Albums.Name AS Album,
		AlbumArtist.Name AS AlbumArtist, AlbumArtist.RomanisedName AS AlbumArtistRomanised,
		TrackArtist.Name AS Artist,
		TrackArtist.RomanisedName AS ArtistRomanised,
		Tracks.Name AS Title,
		Tracks.TrackNumber AS TrackNumber,
		Tracks.AlbumRG AS AlbumRG,
		Tracks.TrackRG AS TrackRG,
		Tracks.MusicBrainzTrackID AS MBID,
		Tracks.SearchKey AS SearchKey
	FROM
		Tracks
		JOIN Albums ON Albums.ID = Tracks.Album
		JOIN Artists AS TrackArtist ON Tracks.Artist = TrackArtist.ID
		JOIN Artists AS AlbumArtist ON Albums.Artist = AlbumArtist.ID;
