#define FIND_AS_YOU_TYPE_INTERVAL ${FIND_AS_YOU_TYPE_INTERVAL}
#cmakedefine EMBEDDED_LEFT_BUTTON_CONTEXT_MENU
#cmakedefine EMBEDDED_USE_FIXED_PATHS

#ifdef EMBEDDED_USE_FIXED_PATHS
#define EMBEDDED_FIXED_DATA_PATH "${EMBEDDED_FIXED_DATA_PATH}"
#define EMBEDDED_FIXED_MUSIC_PATH "${EMBEDDED_FIXED_MUSIC_PATH}"
#endif
